// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADrpUtZcnEC9VmzIPntxwsd5YHerc21P8',
    appId: '1:863651155696:web:658a487b3c29b67921bc35',
    messagingSenderId: '863651155696',
    projectId: 'crud-2303g1',
    authDomain: 'crud-2303g1.firebaseapp.com',
    databaseURL: 'https://crud-2303g1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-2303g1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTJwHaIZGl67aCNgGYxEoiLr6m4ubqRCk',
    appId: '1:863651155696:android:bfcecc5fffe99b7921bc35',
    messagingSenderId: '863651155696',
    projectId: 'crud-2303g1',
    databaseURL: 'https://crud-2303g1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-2303g1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbaNlEAr7KlUDJ_RIbZzFantPcfwPNAPY',
    appId: '1:863651155696:ios:4031b356b0cae8e521bc35',
    messagingSenderId: '863651155696',
    projectId: 'crud-2303g1',
    databaseURL: 'https://crud-2303g1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'crud-2303g1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
