// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQb9WNW3i785vzgiGrqKob75vOFksppOc',
    appId: '1:885782899415:web:ab0d1b46a354cf0106de92',
    messagingSenderId: '885782899415',
    projectId: 'crud-2306c2',
    authDomain: 'crud-2306c2.firebaseapp.com',
    storageBucket: 'crud-2306c2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdT-mbRQ4FffK0WsM6bXpo_yQZV5hKvbY',
    appId: '1:885782899415:android:e0595cbd1920affb06de92',
    messagingSenderId: '885782899415',
    projectId: 'crud-2306c2',
    storageBucket: 'crud-2306c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIOxHAm2UvtTxgRLzqMUEekrCx0H2Rqms',
    appId: '1:885782899415:ios:2e1df0d0f1e0cdd706de92',
    messagingSenderId: '885782899415',
    projectId: 'crud-2306c2',
    storageBucket: 'crud-2306c2.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

}